# Envio HyperIndex Configuration for Asset Nest
# Reference: https://docs.envio.dev/docs/HyperIndex/configuration-file
# Reference: https://docs.envio.dev/docs/HyperIndex/monad-testnet

name: asset-nest-indexer
description: Indexes MetaMask Smart Account events and swap transactions on Monad
version: 1.0.0
envio_version: 2.30.1

# Networks configuration
networks:
  - id: 10143
    name: monad-testnet
    rpc_url: https://testnet-rpc.monad.xyz
    start_block: 0 # Start indexing from genesis or specify a recent block
    hypersync_url: https://monad-testnet.hypersync.xyz # Monad HyperSync endpoint if available

# Contracts to index
contracts:
  # MetaMask Smart Account Factory
  - name: SmartAccountFactory
    address: "0x0000000000000000000000000000000000000000" # Replace with actual factory address
    abi_file_path: ./abis/SmartAccountFactory.json
    handler: ./src/handlers/smartAccountHandler.ts
    events:
      - event: AccountCreated(address indexed account, address indexed owner)
      - event: AccountDeployed(address indexed account)

  # Delegation Manager Contract
  - name: DelegationManager
    address: "0x0000000000000000000000000000000000000001" # Replace with actual delegation manager
    abi_file_path: ./abis/DelegationManager.json
    handler: ./src/handlers/delegationHandler.ts
    events:
      - event: DelegationCreated(address indexed delegator, address indexed delegate, bytes32 indexed delegationHash)
      - event: DelegationRedeemed(address indexed delegate, bytes32 indexed delegationHash)
      - event: DelegationRevoked(address indexed delegator, bytes32 indexed delegationHash)

  # Monorail Swap Router (for tracking trades)
  - name: MonorailRouter
    address: "0x0000000000000000000000000000000000000002" # Replace with actual Monorail router
    abi_file_path: ./abis/MonorailRouter.json
    handler: ./src/handlers/swapHandler.ts
    events:
      - event: Swap(address indexed sender, address indexed recipient, address tokenIn, address tokenOut, uint256 amountIn, uint256 amountOut)

# Field selection for GraphQL schema
field_selection:
  transaction_fields:
    - "hash"
    - "from"
    - "to"
    - "value"
    - "gas_price"
    - "gas_used"
    - "block_number"
    - "block_timestamp"

  log_fields:
    - "address"
    - "topics"
    - "data"
    - "transaction_hash"
    - "block_number"
    - "log_index"

# Global handler configuration
global_handlers:
  - handler: ./src/handlers/globalHandler.ts
    events: ["all"]

# Rollback configuration
rollback_config:
  save_full_history: true
  max_rollback_depth: 1000
